import React from 'react';

interface Props {
  className?: string;
}

export default function ReportDisclaimer({ className = "" }: Props) {
  const appName = (import.meta.env.VITE_APP_NAME as string) || "Aura Estates";
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return (
    <div className={`text-xs text-muted-foreground border-t border-border pt-4 mt-6 ${className}`}>
      <p className="mb-1">
        This report was generated by {appName} Intelligence Platform on {currentDate}
      </p>
      <p>
        Data sourced from Bridge Data Output API. For informational purposes only.
      </p>
    </div>
  );
}